apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diamadio
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - diamadio.agvm
      secretName: diamadio-tls
  rules:
    - host: diamadio.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diamadio
                port:
                  number: 80
