apiVersion: v1
kind: Secret
metadata:
  name: servicesuggestion-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER_NAME: "${DB_USER_NAME}"
  GATEWAY_API_URL: "${GATEWAY_API_URL}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASENAME: "${DB_DATABASENAME}"
