apiVersion: v1
kind: Secret
metadata:
  name: criv-admin-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  VITE_API_URL: "${VITE_API_URL}"
  VITE_WS_URL: "${VITE_WS_URL}"
  VITE_APP_URL: "${VITE_APP_URL}"
  VITE_REGISTER_URL: "${VITE_REGISTER_URL}"
  VITE_REGISTER_USER_URL: "${VITE_REGISTER_USER_URL}"
  VITE_FORGOT_PASSWORD_URL: "${VITE_FORGOT_PASSWORD_URL}"
  VITE_PORT: "${VITE_PORT}"