apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: pnud-agvm
spec:
  selector:
    app: feedback
  ports:
    - protocol: TCP
      port: 4018
      targetPort: 4018
      nodePort: 30053
  type: NodePort