apiVersion: v1
kind: Service
metadata:
  name: servicecontroledelegalite-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicecontroledelegalite
  ports:
    - protocol: TCP
      port: 5043
      targetPort: 5043
      nodePort: 30143