apiVersion: v1
kind: Service
metadata:
  name: matac-commune-service
  namespace: pnud-agvm
spec:
  selector:
    app: matac-commune
  ports:
    - protocol: TCP
      port: 4016
      targetPort: 4016
      nodePort: 30051
  type: NodePort