apiVersion: v1
kind: Service
metadata:
  name: servicesignal-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: servicesignal
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30012
