apiVersion: v1
kind: Service
metadata:
  name: serviceressource-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: serviceressource
  ports:
    - protocol: TCP
      port: 5031
      targetPort: 5031
      nodePort: 30131
