apiVersion: v1
kind: Secret
metadata:
  name: mobilite-urbaine-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  VITE_API_BASE_URL: ${VITE_API_BASE_URL}
  VITE_API_BASE_URL_DEFAULT: ${VITE_API_BASE_URL_DEFAULT}
  VITE_IZOTRA_URL: ${VITE_IZOTRA_URL}
  VITE_REGISTER_URL: ${VITE_REGISTER_URL}
  VITE_FORGOT_PWD_URL: ${VITE_FORGOT_PWD_URL}
  VITE_OSRM_URL: ${VITE_OSRM_URL}
  VITE_TERRITORY_V2_URL: ${VITE_TERRITORY_V2_URL}
  VITE_APK_FILE_NAME: ${VITE_APK_FILE_NAME}
  VITE_APP_ID: ${VITE_APP_ID}
  VITE_APP_MOBILE_ID: ${VITE_APP_MOBILE_ID}
  VITE_PORT: ${VITE_PORT}
  FULL_IMAGE_NAME: ${FULL_IMAGE_NAME}