apiVersion: v1
kind: Secret
metadata:
  name: serviceflotte-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST : "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  GATEWAY_BASE_URL: "${GATEWAY_BASE_URL}"
  GATEWAY_TIMEOUT_MS: "5000"
  NODE_ENV: "production"
