apiVersion: v1
kind: Service
metadata:
  name: serviceauth-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: serviceauth
  ports:
    - protocol: TCP
      port: 5021
      targetPort: 5021
      nodePort: 30031
